Update README.md
PSPDFKit/awesome-nutrient pull request #56
Opened 2024-09-10 09:16 UTC by 0mar-K

Added the following example: Store Signatures in LocalStorage

2024-09-11 07:56 UTC, Siddharth2001-July requested changes
There are two links in brackets. Please remove `[https://github.com/PSPDFKit/awesome-pspdfkit/tree/master/web/Signing/SigningDemoVanillaJS]`

2025-01-16 11:10 UTC, 0mar-K commented
> There are two links in brackets. Please remove `[https://github.com/PSPDFKit/awesome-pspdfkit/tree/master/web/Signing/SigningDemoVanillaJS]`

It's done! I'm so sorry that slipped away, @Siddharth2001-July

2025-01-17 19:01 UTC, jonaddams approved these changes

2025-01-24 20:03 UTC, jonaddams commented
@0mar-K There appears to be some conflicts to resolve on this before it can be merged.

2025-01-28 17:45 UTC, 0mar-K commented
@deutschbitte , may I please have your help resolve these conflicts

2025-01-28 18:24 UTC, deutschbitte commented
@0mar-K Sorry, I don't have write access to this repo. Maybe ask in web.

2025-01-29 11:41 UTC, closed without merging

2025-01-29 11:41 UTC, 0mar-K commented
I'll create a new PR with the above example